apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: simple-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway # Match the label of the ingress gateway
  action: CUSTOM
  provider:
    name: simple-auth
  rules:
    - to:
        - operation:
            paths: ["/home", "/mario"]
